Enforce type hints in flp.py, flp_generic.py and tests
This revealed that the "associated type" pattern we're
following is not enforceable.

For example, we currently do something like this:

```
class Foo:
    # We expect this to be set by the superclass.
    Measurement = None
    def foo(self, bar: Measurement): pass
```

Running `sage -python -m mypy hella.py`:

```
hella.py:4: error: Variable "hella.Foo.Measurement" is not valid as a type  [valid-type]
hella.py:4: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
Found 1 error in 1 file (checked 1 source file)
```

So let's make `Measurement` a type: